// src/utils/diagnosticStructure.ts

export const diagnosticStructure = {
  Biochemistry: [
    'Urea',
    'Sodium',
    'Chloride',
    'Calcium',
    'Phosphate',
    'Liver Function Tests (LFTs)',
    'Lipase',
    'Albumin',
    'Creatinine',
    'Potassium',
    'Bicarbonate',
    'Magnesium',
    'Glucose',
    'Amylase',
    'Total Protein',
  ],
  Hematology: [
    'Full Blood Count (FBC)',
    'ESR',
    'Peripheral Smear',
    'Reticulocyte Count',
    'Platelet Count',
    'Coagulation Profile',
    'INR',
    'PT',
    'aPTT',
  ],
  Endocrinology: [
    'Thyroid Stimulating Hormone (TSH)',
    'Free T3',
    'Free T4',
    'Cortisol',
    'Insulin',
    'HbA1c',
    'Parathyroid Hormone (PTH)',
    'ACTH',
  ],
  Cardiology: [
    'ECG',
    'Troponin I',
    'Cardiac Enzymes',
    'CK-MB',
    'Lipid Profile',
  ],
  Imaging: [
    'Chest X-Ray',
    'CT Brain',
    'MRI Brain',
    'Ultrasound Abdomen',
    'Breast Ultrasound',
    'Abdominal X-Ray',
    'CT Abdomen',
    'MRI Spine',
    'Pelvic Ultrasound',
  ],
  PointOfCare: [
    'Urine Dipstick',
    'Rapid HIV Test',
    'Blood Glucose (Fingerprick)',
    'Pregnancy Test',
    'Rapid Malaria Test',
  ],
  TumorMarkers: [
    'AFP',
    'CEA',
    'CA-125',
    'PSA',
    'Beta-hCG',
  ],
};
