// src/utils/staticAppPhrases.ts

export const staticAppPhrases: string[] = [
  // 📁 General Pages
  "Patients",
  "Critical Alerts",
  "Upcoming Cases",
  "Slates",
  "Consultations",
  "Prescriptions",
  "Blood Results",
  "Imaging Results",
  "Diagnostics",
  "Referrals",
  "Notes",
  "Tasks",
  "Appointments",
  "Receptionist View",
  "Hospital's View",
  "Staff/Role Management",
  "System Settings",

  // ⚙️ System Buttons / Labels
  "Add Patient",
  "Escalate",
  "Download PDF",
  "Upload File",
  "Search tests",
  "Order Investigation",
  "Role Expiry",
  "Create Task",
  "Add Appointment",
  "Vitals",
  "Triage",
  "Medical Aid",
  "Emergency Contact",
  "Comorbidities",
  "Allergies",
  "Notes",
  "Prescriptions",
  "Reports",
  "Save",
  "Cancel",
  "Delete",

  // 🧪 Lab Categories (match your diagnosticStructure)
  "Biochemistry",
  "Hematology",
  "Endocrinology",
  "Tumor Markers",
  "Infectious Diseases",
  "Toxicology",
  "Urinalysis",
  "Serology",
  "Radiology",
  "Cardiology",
  "Genetic Tests",
  "Immunology",
  "Microbiology",
  "Virology",
  "CT Scan",
  "MRI",
  "Ultrasound",
  "X-Ray",

  // 🧑‍⚕️ Roles
  "Doctor",
  "Receptionist",
  "Admin",
  "Nurse",
  "Assistant",
  "Specialist",
];
